name: "💡 Feature Request"
description: "Suggest a new idea or improvement"
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: "### Got an idea? Let's make this project better 🚀"
  - type: input
    id: feature
    attributes:
      label: "Feature name"
      placeholder: "What do you want to add?"
  - type: textarea
    id: description
    attributes:
      label: "Describe your feature"
      placeholder: "Explain your idea..."
  - type: textarea
    id: benefits
    attributes:
      label: "Why is it useful?"
      placeholder: "Why should we add this?"
